### PR TITLE
Parsers refactoring

### PR DESCRIPTION
**Pull request by darrengarvey**
Simplification to parsers code by making it more generic.

### CODE REVIEW

**Comment by darrengarvey** [comment]
@formiaczek Can you fix up the conflict and I'll merge this in. Thanks! I've got something to on top of it.

**Comment by formiaczek** [comment]
Hey @darrengarvey : rebased & ready to merge :)

**Comment by formiaczek** [comment]
:)

**Comment by lukaszforynski** [comment]
Ping :) How are you Darren?

**Comment by darrengarvey** [comment]
I'm good @lukaszforynski. How are you? :) Send me your personal email sir. Thanks for the splendiferous contribution. Sorry it took so long for me to check it worked fine. I guess that means I need to add more tests!

**Pull request merged**
